# Generated by Django 5.2.1 on 2025-08-23 21:20

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupPDO',
            fields=[
                ('pdoID', models.AutoField(primary_key=True, serialize=False)),
                ('pdo_title', models.CharField(help_text='Enter the Project Development Objective title', max_length=300, unique=True)),
                ('pdo_description', models.TextField(help_text='Detailed description of the PDO')),
                ('pdo_indicator', models.CharField(blank=True, help_text='Key performance indicator for this PDO', max_length=500, null=True)),
                ('target_value', models.CharField(blank=True, help_text='Target value or outcome expected', max_length=100, null=True)),
                ('baseline_value', models.CharField(blank=True, help_text='Baseline value at project start', max_length=100, null=True)),
                ('target_date', models.DateField(blank=True, help_text='Expected completion date for this PDO', null=True)),
                ('responsible_unit', models.CharField(blank=True, help_text='Unit or department responsible for this PDO', max_length=200, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('achieved', 'Achieved'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='not_started', help_text='Current status of the PDO', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this PDO is currently active')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_pdos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Development Objective',
                'verbose_name_plural': 'Project Development Objectives',
                'ordering': ['-date'],
            },
        ),
    ]
