# Generated by Django 5.2.1 on 2025-07-07 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PIU_Financial_mgt', '0001_initial'),
        ('setup', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_Profiling_goods_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amendments', models.BooleanField(default=False)),
                ('contract_refNo', models.CharField(max_length=50)),
                ('name_of_Supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_consultant', models.CharField(max_length=200)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('duration', models.CharField(max_length=10)),
                ('remarks', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('activityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.activities')),
                ('compID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.component')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.currency')),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.donor')),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiling_goods_and_services', to=settings.AUTH_USER_MODEL)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project')),
                ('project_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.projectcategory')),
                ('subcompID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.subcomponent')),
            ],
            options={
                'verbose_name': 'Contract Profiling Goods & Services',
                'verbose_name_plural': 'Contract Profiling Goods & Services ',
            },
        ),
        migrations.CreateModel(
            name='Contract_Profiling_works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_intervention_focus_result', models.CharField(blank=True, max_length=500, null=True)),
                ('target_number_of_beneficiary_settlements', models.IntegerField(blank=True, null=True)),
                ('location_of_investment', models.CharField(blank=True, max_length=500, null=True)),
                ('Latitude', models.FloatField(null=True)),
                ('Longitude', models.FloatField(null=True)),
                ('gross_floor_area_m2', models.IntegerField(null=True)),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amendments', models.BooleanField(default=False)),
                ('contract_refNo', models.CharField(max_length=50)),
                ('name_of_contractor', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_consultant', models.CharField(max_length=200)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('duration', models.CharField(max_length=10)),
                ('remarks', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('activityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.activities')),
                ('compID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.component')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.currency')),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.donor')),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiling_works', to=settings.AUTH_USER_MODEL)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project')),
                ('project_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.projectcategory')),
                ('subcompID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.subcomponent')),
            ],
            options={
                'verbose_name': 'Contract Profiling works',
                'verbose_name_plural': 'Contract Profiling works',
            },
        ),
        migrations.CreateModel(
            name='Specific_Contract_Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_refNo', models.CharField(max_length=50, verbose_name='Contract Reference Number')),
                ('monitoring_date', models.DateField(default=django.utils.timezone.now, verbose_name='Monitoring Date')),
                ('milestone_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Milestone Start Date')),
                ('milestone_end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Milestone End Date')),
                ('Target', models.TextField(verbose_name='Target')),
                ('Achieved_status', models.TextField(verbose_name='Achieved Status')),
                ('picture_of_status', models.ImageField(blank=True, null=True, upload_to='images/project_actions', verbose_name='Picture of Status')),
                ('remarks', models.TextField(verbose_name='Remarks')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('Contract_implementation_Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.physicalprogress', verbose_name='Contract Implementation Status')),
                ('Kpi_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_contract_investments', to='PIU_Financial_mgt.kpi_for_contract', verbose_name='KPI Description')),
                ('Type_of_Investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_types', to='PIU_Financial_mgt.kpi_for_contract', verbose_name='Type of Investment')),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Specific_Contract_Monitoring', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project', verbose_name='Project')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.quarter', verbose_name='Report Frequency')),
                ('type_of_monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.type_of_monitoring', verbose_name='Type of Monitoring')),
            ],
            options={
                'verbose_name': 'Specific Contract Monitoring',
                'verbose_name_plural': 'Specific Contract Monitoring',
            },
        ),
    ]
