# Generated by Django 5.2.1 on 2025-10-01 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PIU_Financial_mgt', '__latest__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_funding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('disbursement', models.DecimalField(decimal_places=2, max_digits=12)),
                ('over_all_disbursement_rate', models.DecimalField(decimal_places=2, help_text='Percentage value (0-100)', max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project')),
            ],
        ),
    ]
