# Generated by Django 5.2.1 on 2025-10-01 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PIU_Financial_mgt', '__latest__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_funding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('disbursement', models.DecimalField(decimal_places=2, max_digits=12)),
                ('over_all_disbursement_rate', models.CharField(max_length=10)),
                ('over_all_physical_progress', models.CharField(max_length=10)),
                ('over_project_time_elapsed', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project')),
                ('loginuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Project Progress',
                'verbose_name_plural': 'Project Progress',
                'ordering': ['-date_created'],
            },
        ),
    ]
