# Generated by Django 5.2.1 on 2025-07-07 14:33

import django.core.validators
import django.db.models.deletion
import social_and_env.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PIU_Financial_mgt', '0001_initial'),
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityConsult_Engagement',
            fields=[
                ('reference_number', models.CharField(help_text='Unique reference number for this engagement', max_length=15, primary_key=True, serialize=False, unique=True)),
                ('place_of_event', models.CharField(help_text='Location where engagement took place', max_length=100)),
                ('date_of_consultation', models.DateField(db_index=True)),
                ('male', models.PositiveIntegerField(help_text='Number of male participants', validators=[django.core.validators.MinValueValidator(0)])),
                ('female', models.PositiveIntegerField(help_text='Number of female participants', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_participants', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('key_issues_discussed', models.TextField()),
                ('any_follow_up_actions', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, help_text='Upload engagement photos', null=True, upload_to='images/communityConsultation', verbose_name='Picture')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project', verbose_name='Name of Project')),
                ('stake_holder_engagement_Types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.typeofstakeholderengagement')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.year')),
            ],
            options={
                'verbose_name': 'Community Engagement/Consultation',
                'verbose_name_plural': 'Community Engagement/Consultations',
                'ordering': ['-date_of_consultation', '-date_created'],
                'indexes': [models.Index(fields=['project_name', 'year'], name='social_and__project_18eb69_idx'), models.Index(fields=['stake_holder_engagement_Types'], name='social_and__stake_h_3e90d3_idx'), models.Index(fields=['date_of_consultation', 'place_of_event'], name='social_and__date_of_42cb17_idx'), models.Index(fields=['male', 'female', 'total_participants'], name='social_and__male_20fd26_idx')],
            },
        ),
        migrations.CreateModel(
            name='ESIA',
            fields=[
                ('esiaID', models.AutoField(primary_key=True, serialize=False)),
                ('project_duration', models.PositiveIntegerField(help_text='Duration in months (1-120)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('project_phase', models.PositiveIntegerField(help_text='Phase number (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('project_locations', models.CharField(help_text='Comma-separated list of project locations', max_length=200)),
                ('number_of_communities', models.PositiveIntegerField(help_text='Number of communities affected', validators=[django.core.validators.MinValueValidator(1)])),
                ('esia_findings', models.TextField(help_text='Detailed findings of the ESIA study')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esia_entries', to='PIU_Financial_mgt.project')),
                ('type_of_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.kpi_for_contract')),
            ],
            options={
                'verbose_name': 'ESIA',
                'verbose_name_plural': 'ESIA',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['project_name', 'type_of_investment'], name='social_and__project_41aa82_idx'), models.Index(fields=['date_created', 'loginUser'], name='social_and__date_cr_553c5c_idx'), models.Index(fields=['project_phase', 'number_of_communities'], name='social_and__project_a8c82f_idx')],
            },
        ),
        migrations.CreateModel(
            name='GrievianceMonitoringLog',
            fields=[
                ('case_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1, null=True)),
                ('date_claim_recieved', models.DateField(db_index=True)),
                ('name_of_person_receiving_complaint', models.CharField(max_length=150)),
                ('how_complaint_was_received', models.CharField(choices=[('Call', 'Phone Call'), ('Email', 'Email'), ('Letter', 'Letter'), ('In Person', 'In Person'), ('SMS', 'SMS'), ('WhatsApp', 'WhatsApp')], db_index=True, max_length=20)),
                ('name_of_complainant', models.CharField(max_length=150)),
                ('tell_no', models.CharField(help_text='Phone number', max_length=20)),
                ('complaint_content', models.TextField()),
                ('was_recieved_of_complaint_ack', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_index=True, max_length=1, verbose_name='Complaint acknowledgment received')),
                ('expected_decision_date', models.DateField(db_index=True)),
                ('was_decison_communicated_to_complainant', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_index=True, max_length=1, verbose_name='Decision communicated to complainant')),
                ('communication_method', models.CharField(choices=[('Call', 'Phone Call'), ('Email', 'Email'), ('Letter', 'Letter'), ('In Person', 'In Person'), ('SMS', 'SMS'), ('WhatsApp', 'WhatsApp')], db_index=True, max_length=20)),
                ('was_complainant_satisfied_with_decision', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_index=True, max_length=1, verbose_name='Complainant satisfied with decision')),
                ('brief_note_for_NO_answer', models.TextField(blank=True, verbose_name='Explanation if not satisfied')),
                ('any_follow_up_action', models.TextField(blank=True, verbose_name='Follow-up Actions')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decision_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.decisionoutcome')),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project')),
                ('type_of_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.kpi_for_contract')),
            ],
            options={
                'verbose_name': 'Grievance Case',
                'verbose_name_plural': 'Grievance Cases',
                'ordering': ['-date_claim_recieved', '-date_created'],
                'indexes': [models.Index(fields=['project', 'type_of_investment'], name='social_and__project_cc9315_idx'), models.Index(fields=['decision_outcome', 'communication_method'], name='social_and__decisio_2b3a59_idx'), models.Index(fields=['sex', 'how_complaint_was_received'], name='social_and__sex_aef3cc_idx'), models.Index(fields=['date_claim_recieved', 'expected_decision_date'], name='social_and__date_cl_d3d5a8_idx'), models.Index(fields=['was_complainant_satisfied_with_decision'], name='social_and__was_com_59cd54_idx')],
            },
        ),
        migrations.CreateModel(
            name='OHS_Monitoring',
            fields=[
                ('ohs_Id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='Monitoring Date')),
                ('quality_at_entry_requirement', models.TextField(help_text='Staffing, training, medicals, code of conduct, contracts')),
                ('working_environment', models.TextField()),
                ('remarks', models.TextField(blank=True, default='', verbose_name='Issues or Remarks')),
                ('male', models.PositiveIntegerField(help_text='Number of male workers', validators=[django.core.validators.MinValueValidator(0)])),
                ('female', models.PositiveIntegerField(help_text='Number of female workers', validators=[django.core.validators.MinValueValidator(0)])),
                ('youth_male', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Male Youths')),
                ('youth_female', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Female Youths')),
                ('picture', models.ImageField(blank=True, help_text='Upload monitoring photos', null=True, upload_to=social_and_env.models.image_upload_path, verbose_name='Picture')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('Kpi_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohs_kpi_descriptions', to='PIU_Financial_mgt.kpi_for_contract')),
                ('Type_of_Investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohs_investments', to='PIU_Financial_mgt.kpi_for_contract')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.districts')),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project', verbose_name='Project')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.quarter', verbose_name='Report Frequency')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.regions')),
                ('settlement', models.ForeignKey(db_column='settlement_id', on_delete=django.db.models.deletion.CASCADE, to='setup.settlement')),
                ('year_of_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.year')),
            ],
            options={
                'verbose_name': 'OHS Monitoring',
                'verbose_name_plural': 'OHS Monitoring',
                'ordering': ['-date', '-date_created'],
                'indexes': [models.Index(fields=['project', 'Type_of_Investment'], name='social_and__project_c40fe8_idx'), models.Index(fields=['year_of_report', 'quarter'], name='social_and__year_of_6a06cf_idx'), models.Index(fields=['region', 'district', 'settlement'], name='social_and__region__3d84d0_idx'), models.Index(fields=['date', 'loginUser'], name='social_and__date_b24fb4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PAP',
            fields=[
                ('pap_identification_number', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='PAP ID')),
                ('pap_name', models.CharField(max_length=150)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1)),
                ('location_of_impact', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('area', models.CharField(help_text='Area affected (in hectares)', max_length=20)),
                ('pap_compensated', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_index=True, max_length=1)),
                ('compensation_date', models.DateField(blank=True, db_index=True, null=True)),
                ('compensation_RefNo', models.CharField(blank=True, max_length=30)),
                ('pre_project_situation', models.TextField(help_text='Describe the situation before project implementation', verbose_name='Pre-project situation')),
                ('remarks', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.districts')),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nature_of_compensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.natureofsettlement')),
                ('pap_Current_Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.settlement')),
                ('pap_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.papcategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.regions')),
                ('type_of_impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.typeofimpact')),
                ('type_of_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.kpi_for_contract')),
                ('type_of_pap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.typeofpap')),
                ('vulnerability_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.vulnerabilitycategory')),
            ],
            options={
                'verbose_name': 'PAP',
                'verbose_name_plural': 'PAP',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['project', 'type_of_investment'], name='social_and__project_52441a_idx'), models.Index(fields=['region', 'district', 'pap_Current_Address'], name='social_and__region__6a5854_idx'), models.Index(fields=['pap_compensated', 'compensation_date'], name='social_and__pap_com_25b78f_idx'), models.Index(fields=['sex', 'vulnerability_category'], name='social_and__sex_974028_idx'), models.Index(fields=['type_of_pap', 'pap_category'], name='social_and__type_of_db7e2e_idx')],
            },
        ),
    ]
