# Generated by Django 4.2.4 on 2025-08-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_and_env', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pap',
            name='document_upload',
            field=models.FileField(blank=True, help_text='Upload document (PDF, Word, Excel, Images - max 10MB)', null=True, upload_to='documents/pap/'),
        ),
    ]