# Generated by Django 5.2.1 on 2025-08-20 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import social_and_env.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_and_env', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAPDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('title_deed', 'Title Deed'), ('id_document', 'ID Document'), ('compensation_agreement', 'Compensation Agreement'), ('valuation_report', 'Valuation Report'), ('other', 'Other Document')], db_index=True, default='title_deed', max_length=50)),
                ('document_file', models.FileField(help_text='Upload document (PDF, DOC, DOCX, JPG, PNG - Max 10MB)', upload_to=social_and_env.models.pap_document_upload_path)),
                ('document_name', models.CharField(help_text='Document description or name', max_length=200)),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pap', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='social_and_env.pap')),
                ('uploaded_by', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PAP Document',
                'verbose_name_plural': 'PAP Documents',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['pap', 'document_type'], name='social_and__pap_id_84a59f_idx'), models.Index(fields=['upload_date', 'uploaded_by'], name='social_and__upload__4e0b73_idx')],
            },
        ),
    ]
