# Generated by Django 5.2.1 on 2025-07-07 14:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PIU_Financial_mgt', '0001_initial'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nawecinfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scode', models.CharField(max_length=50)),
                ('No_of_Transfprmer', models.IntegerField()),
                ('transformer_name', models.CharField(max_length=10)),
                ('No_of_Households_With_Electricity', models.IntegerField()),
                ('water_supply_source', models.CharField(max_length=25)),
                ('No_of_Households_With_water', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='settlementwithCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=25)),
                ('lga', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('settlement_code', models.CharField(max_length=25)),
                ('settlement_name', models.CharField(max_length=100)),
                ('population_household', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(13.0), django.core.validators.MaxValueValidator(14.0)])),
                ('Longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-14.0), django.core.validators.MaxValueValidator(-18.0)])),
            ],
        ),
        migrations.CreateModel(
            name='projectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_No_of_Households', models.IntegerField()),
                ('no_of_connected_household', models.IntegerField(null=True)),
                ('no_of_customer_connections', models.IntegerField(null=True)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.access')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.districts')),
                ('donor', models.ManyToManyField(to='setup.donor')),
                ('profile_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.year')),
                ('project', models.ManyToManyField(to='PIU_Financial_mgt.project')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.regions')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.settlement', verbose_name='settlement_name')),
            ],
        ),
    ]
