# Generated by Django 5.2.1 on 2025-07-26 04:54

from django.db import migrations, models
import django.db.models.deletion


def migrate_project_data(apps, schema_editor):
    """Convert ManyToMany project relationships to ForeignKey"""
    projectMapping = apps.get_model('PIU_Mapping_project_Sites', 'projectMapping')
    
    # Get all mappings with their first project (take the first one for single select)
    for mapping in projectMapping.objects.all():
        first_project = mapping.project.first()
        if first_project:
            # Update the new project_id field
            projectMapping.objects.filter(pk=mapping.pk).update(temp_project_id=first_project.pk)


def reverse_migrate_project_data(apps, schema_editor):
    """Reverse migration - convert ForeignKey back to ManyToMany"""
    projectMapping = apps.get_model('PIU_Mapping_project_Sites', 'projectMapping')
    
    # Add back the ManyToMany relationships
    for mapping in projectMapping.objects.all():
        if mapping.temp_project_id:
            mapping.project.add(mapping.temp_project_id)


class Migration(migrations.Migration):

    dependencies = [
        ('PIU_Financial_mgt', '0001_initial'),
        ('PIU_Mapping_project_Sites', '0001_initial'),
    ]

    operations = [
        # Step 1: Add temporary ForeignKey field
        migrations.AddField(
            model_name='projectmapping',
            name='temp_project_id',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        
        # Step 2: Migrate data from ManyToMany to temporary field
        migrations.RunPython(migrate_project_data, reverse_migrate_project_data),
        
        # Step 3: Remove old ManyToMany field
        migrations.RemoveField(
            model_name='projectmapping',
            name='project',
        ),
        
        # Step 4: Add new ForeignKey field
        migrations.AddField(
            model_name='projectmapping',
            name='project',
            field=models.ForeignKey(
                null=True, 
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='site_mappings',
                to='PIU_Financial_mgt.project'
            ),
        ),
        
        # Step 5: Copy data from temporary field to new ForeignKey
        migrations.RunSQL(
            "UPDATE PIU_Mapping_project_Sites_projectmapping SET project_id = temp_project_id WHERE temp_project_id IS NOT NULL;",
            reverse_sql="UPDATE PIU_Mapping_project_Sites_projectmapping SET temp_project_id = project_id WHERE project_id IS NOT NULL;"
        ),
        
        # Step 6: Remove temporary field
        migrations.RemoveField(
            model_name='projectmapping',
            name='temp_project_id',
        ),
        
        # Step 7: Make project field non-nullable (optional - you can skip this if you want to allow null)
        # migrations.AlterField(
        #     model_name='projectmapping',
        #     name='project',
        #     field=models.ForeignKey(
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name='site_mappings',
        #         to='PIU_Financial_mgt.project'
        #     ),
        # ),
    ]
