# Generated by Django 5.2.1 on 2025-07-26 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIU_Mapping_project_Sites', '0002_auto_20250726_0454'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmapping',
            name='access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_mappings', to='setup.access'),
        ),
        migrations.AlterField(
            model_name='projectmapping',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_mappings', to='setup.districts'),
        ),
        migrations.AlterField(
            model_name='projectmapping',
            name='donor',
            field=models.ManyToManyField(related_name='site_mappings', to='setup.donor'),
        ),
        migrations.AlterField(
            model_name='projectmapping',
            name='profile_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_mappings', to='setup.year'),
        ),
        migrations.AlterField(
            model_name='projectmapping',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_mappings', to='setup.regions'),
        ),
        migrations.AlterField(
            model_name='projectmapping',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_mappings', to='setup.settlement', verbose_name='settlement_name'),
        ),
    ]
