# Generated by Django 5.2.1 on 2025-07-07 14:33

import Project_Documentation_Tracking.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PIU_Financial_mgt', '0001_initial'),
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Documentation_Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('document_date', models.DateField()),
                ('attachment', models.FileField(upload_to=Project_Documentation_Tracking.models.document_upload_path)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.documenttype')),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project')),
            ],
            options={
                'verbose_name': 'Project Documentation Tracking',
                'verbose_name_plural': 'Project Documentation Tracking ',
            },
        ),
    ]
