# Generated by Django 5.2.1 on 2025-07-11 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Documentation_Tracking', '0001_initial'),
    ]

    operations = [
    ]
