# Generated by Django 5.2.1 on 2025-07-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Documentation_Tracking', '0002_auto_20250711_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='project_documents/', verbose_name='Document File'),
        ),
    ]
