# Generated by Django 5.2.1 on 2025-07-07 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('region_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Region',
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(max_length=30, unique=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'access_type',
                'verbose_name_plural': 'access_type',
            },
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('contriID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contributors',
                'verbose_name_plural': 'Contributors',
            },
        ),
        migrations.CreateModel(
            name='Data_Collection_Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=50, unique=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_freq', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Collection Frequency',
                'verbose_name_plural': 'Data Collection Frequency',
            },
        ),
        migrations.CreateModel(
            name='DecisionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=20)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Decision OutCome',
                'verbose_name_plural': 'Decision OutCome',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_of_document', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Type Of Document',
                'verbose_name_plural': 'Type of Documents',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donorID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donor',
            },
        ),
        migrations.CreateModel(
            name='Indicator_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(max_length=500, unique=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indicator Type',
                'verbose_name_plural': 'Indicator Type',
            },
        ),
        migrations.CreateModel(
            name='Measurement_Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50, unique=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measuring_unit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Measuring Unit',
                'verbose_name_plural': 'Measuring Unit',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'month',
                'verbose_name_plural': 'months',
            },
        ),
        migrations.CreateModel(
            name='NatureOfSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_settlement', models.CharField(max_length=50, unique=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nature_of_settlement',
                'verbose_name_plural': 'Nature Of Settlement',
            },
        ),
        migrations.CreateModel(
            name='PAPCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pap_category', models.CharField(max_length=70, unique=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papcategories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PAP Category',
                'verbose_name_plural': 'PAP Category',
            },
        ),
        migrations.CreateModel(
            name='Physicalprogress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_scale', models.CharField(max_length=20, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physicalprogress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Physical progress',
                'verbose_name_plural': 'Physical progress',
            },
        ),
        migrations.CreateModel(
            name='project_Activity_monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=150, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_activities_monitoring', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Type',
                'verbose_name_plural': 'Activity Types',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, unique=True)),
                ('category_Description', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Category',
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=15, unique=True, verbose_name='Report Frequency')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quarter',
                'verbose_name_plural': 'Quarter',
            },
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('lga_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('lga_name', models.CharField(max_length=50, unique=True)),
                ('region_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.regions')),
            ],
            options={
                'verbose_name': 'LGA',
                'verbose_name_plural': 'LGA',
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('district_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=100, unique=True)),
                ('lga_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.lga')),
                ('region_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.regions')),
            ],
            options={
                'verbose_name': 'Districts',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_or_no', models.CharField(max_length=10)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yes OR No',
                'verbose_name_plural': 'Yes OR No',
            },
        ),
        migrations.CreateModel(
            name='Type_of_Monitoring',
            fields=[
                ('monitoring_type_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('monitoring_type', models.CharField(max_length=25, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_of_monitoring', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Type Of Monitoring',
                'verbose_name_plural': 'Type Of Monitoring',
            },
        ),
        migrations.CreateModel(
            name='TypeOfImpact',
            fields=[
                ('impact_number', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('impact', models.CharField(max_length=150, unique=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_type', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impact',
                'verbose_name_plural': 'Type Of Impact',
            },
        ),
        migrations.CreateModel(
            name='TypeOfInvestment',
            fields=[
                ('investmentID', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_investment', models.CharField(max_length=100, unique=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_type', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Type of Investment',
                'verbose_name_plural': 'Type of Investment',
            },
        ),
        migrations.CreateModel(
            name='TypeOfPAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_pap', models.CharField(max_length=70, unique=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paptypes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Type of PAP',
                'verbose_name_plural': 'Type of PAP',
            },
        ),
        migrations.CreateModel(
            name='TypeOfStakeholderEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake_holder_engagement', models.CharField(max_length=150, verbose_name='Consultation/Engagement')),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Type Of Stakeholder Engagement',
                'verbose_name_plural': 'Type Of Stakeholder Engagement',
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability', models.CharField(max_length=30, unique=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability_category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vulnerability category',
                'verbose_name_plural': 'Vulnerability category',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=50, unique=True)),
                ('district_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.districts')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Ward',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('settlement_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('settlement_name', models.CharField(max_length=150)),
                ('EA', models.CharField(max_length=10)),
                ('district_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.districts')),
                ('ward_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.ward')),
            ],
            options={
                'verbose_name': 'Settlement',
                'verbose_name_plural': 'Settlement name',
                'db_table': 'setup_settlement',
            },
        ),
        migrations.CreateModel(
            name='YEAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_year', models.CharField(max_length=4, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Year',
                'verbose_name_plural': 'Profile Year',
            },
        ),
    ]
