# Generated by Django 5.2.1 on 2025-07-07 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=4, unique=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=200, unique=True)),
                ('funding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effectiveness_Date', models.DateField(blank=True, null=True)),
                ('closure_Date', models.DateField(blank=True, null=True)),
                ('last_date_of_Disbursement', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contributors', models.ManyToManyField(to='setup.contributors')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.currency')),
                ('donors', models.ManyToManyField(to='setup.donor')),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='PDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdo_statement', models.CharField(max_length=200, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdos', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project')),
            ],
            options={
                'verbose_name': 'PDO Statement',
                'verbose_name_plural': 'PDO Statements',
            },
        ),
        migrations.CreateModel(
            name='KPI_For_Contract',
            fields=[
                ('type_of_investment', models.TextField()),
                ('Kpi_description', models.TextField()),
                ('monitoring_Type_Code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('monitoring_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.type_of_monitoring')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'KPIs',
                'verbose_name_plural': 'KPIs',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('compID', models.AutoField(primary_key=True, serialize=False, verbose_name='Component')),
                ('Project_Components', models.CharField(max_length=100)),
                ('component_Description', models.CharField(max_length=500)),
                ('allocation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.currency')),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Component',
            },
        ),
        migrations.CreateModel(
            name='ProjectOutCome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_outcome', models.CharField(max_length=200, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectoutcomes', to=settings.AUTH_USER_MODEL)),
                ('pdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.pdo')),
            ],
            options={
                'verbose_name': 'Project Outcome',
                'verbose_name_plural': 'Project Outcomes',
            },
        ),
        migrations.CreateModel(
            name='ProjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_result', models.CharField(max_length=200, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectresults', to=settings.AUTH_USER_MODEL)),
                ('project_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.projectoutcome')),
            ],
            options={
                'verbose_name': 'Project Result',
                'verbose_name_plural': 'Project Results',
            },
        ),
        migrations.CreateModel(
            name='Subcomponent',
            fields=[
                ('subcompID', models.AutoField(primary_key=True, serialize=False)),
                ('subcomponent', models.CharField(max_length=100)),
                ('subcomponent_Description', models.CharField(max_length=500)),
                ('allocation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('compID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.component', verbose_name='Component')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.currency')),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Subcomponent',
                'verbose_name_plural': 'Subcomponents',
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('activityID', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=500, unique=True)),
                ('allocation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.year')),
                ('compID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.component', verbose_name='Component')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.currency')),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project', verbose_name='Project')),
                ('subcompID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.subcomponent', verbose_name='Subcomponent')),
            ],
            options={
                'verbose_name': 'Activities',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
