# Generated by Django 5.2.1 on 2025-08-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PIU_Financial_mgt', '0002_alter_kpi_for_contract_table'),
        ('PIU_Financial_mgt', '0002_update_component_fields'),
    ]

    operations = [
    ]
