# Generated by Django 5.2.1 on 2025-09-01 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PIU_Financial_mgt', '0005_update_subcomponent_field_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdo_statement', models.CharField(max_length=200, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project')),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDO Statement',
                'verbose_name_plural': 'PDO Statements',
            },
        ),
        migrations.AddField(
            model_name='projectoutcome',
            name='pdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.pdo'),
            preserve_default=False,
        ),
    ]
