// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/piu-mobile/Dashboard.tsx": () => import("../components/mockups/piu-mobile/Dashboard.tsx"),
  "./components/mockups/piu-mobile/Drawer.tsx": () => import("../components/mockups/piu-mobile/Drawer.tsx"),
  "./components/mockups/piu-mobile/Login.tsx": () => import("../components/mockups/piu-mobile/Login.tsx"),
  "./components/mockups/piu-mobile/Projects.tsx": () => import("../components/mockups/piu-mobile/Projects.tsx")
};
