# Generated by Django 5.2.1 on 2025-07-12 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAWEC_KPI', '0001_initial'),
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_value', models.FloatField(blank=True, help_text='Baseline value for comparison', null=True)),
                ('End_Target_Value', models.FloatField(blank=True, help_text='End target value to achieve', null=True)),
                ('achieved_value', models.IntegerField(blank=True, choices=[(0, 'Qualified'), (1, 'Unqualified')], help_text='Audit Opinion: 0=Qualified, 1=Unqualified', null=True)),
                ('audit_opinion', models.IntegerField(choices=[(0, 'Qualified'), (1, 'Unqualified')], help_text='Audit Opinion: 0=Qualified, 1=Unqualified')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.quarter')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.year')),
            ],
            options={
                'verbose_name': 'Audit Opinion (AO) Calculation',
                'verbose_name_plural': 'Audit Opinion (AO) Calculations',
            },
        ),
        migrations.CreateModel(
            name='CalculateCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_value', models.FloatField(blank=True, help_text='Baseline value for comparison', null=True)),
                ('End_Target_Value', models.FloatField(blank=True, help_text='End target value to achieve', null=True)),
                ('achieved_value', models.FloatField(blank=True, help_text='Calculated Current Ratio', null=True)),
                ('current_assets', models.FloatField(blank=True, help_text='Current Assets', null=True)),
                ('current_liabilities', models.FloatField(blank=True, help_text='Current Liabilities', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.quarter')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.year')),
            ],
            options={
                'verbose_name': 'Current Ratio (CR) Calculation',
                'verbose_name_plural': 'Current Ratio (CR) Calculations',
            },
        ),
        migrations.CreateModel(
            name='CalculateDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_value', models.FloatField(blank=True, help_text='Baseline value for comparison', null=True)),
                ('End_Target_Value', models.FloatField(blank=True, help_text='End target value to achieve', null=True)),
                ('achieved_value', models.FloatField(blank=True, help_text='Calculated Debt to Equity Ratio', null=True)),
                ('total_debt', models.FloatField(blank=True, help_text='Total Debt', null=True)),
                ('total_equity', models.FloatField(blank=True, help_text='Total Equity', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.quarter')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.year')),
            ],
            options={
                'verbose_name': 'Debt to Equity Ratio (DER) Calculation',
                'verbose_name_plural': 'Debt to Equity Ratio (DER) Calculations',
            },
        ),
    ]
