# Generated by Django 5.2.1 on 2025-07-12 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAWEC_KPI', '0002_calculateao_calculatecr_calculateder'),
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatePARI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_value', models.FloatField(blank=True, help_text='Baseline value for comparison', null=True)),
                ('End_Target_Value', models.FloatField(blank=True, help_text='End target value to achieve', null=True)),
                ('achieved_value', models.FloatField(blank=True, help_text='Calculated PARI percentage', null=True)),
                ('total_recommendations', models.IntegerField(blank=True, help_text='Total Number of Recommendations', null=True)),
                ('total_implemented', models.IntegerField(blank=True, help_text='Total Implemented', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.quarter')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.year')),
            ],
            options={
                'verbose_name': 'PARI (Percentage Audit Recommendations Implementation) Calculation',
                'verbose_name_plural': 'PARI (Percentage Audit Recommendations Implementation) Calculations',
            },
        ),
    ]
