# Generated by Django 5.2.1 on 2025-07-12 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAWEC_KPI', '0003_calculatepari'),
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatepari',
            name='total_recommendations',
        ),
        migrations.AddField(
            model_name='calculatepari',
            name='total_number_of_recommendations',
            field=models.FloatField(blank=True, help_text='total_number_of_recommendations', null=True),
        ),
        migrations.AlterField(
            model_name='calculatepari',
            name='achieved_value',
            field=models.FloatField(blank=True, help_text='Calculated Current Ratio', null=True),
        ),
        migrations.AlterField(
            model_name='calculatepari',
            name='total_implemented',
            field=models.FloatField(blank=True, help_text='total implemented', null=True),
        ),
        migrations.CreateModel(
            name='CalculateTSQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_value', models.FloatField(blank=True, help_text='Baseline value for comparison', null=True)),
                ('End_Target_Value', models.FloatField(blank=True, help_text='End target value to achieve', null=True)),
                ('achieved_value', models.FloatField(blank=True, help_text='Calculated TSQR ratio', null=True)),
                ('due_date', models.IntegerField(blank=True, help_text='Due Date (A) - in days', null=True)),
                ('actual_date', models.IntegerField(blank=True, help_text='Actual Date (B) - in days', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.quarter')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.year')),
            ],
            options={
                'verbose_name': 'Timely Submission of Quarterly Report (TSQR) Calculation',
                'verbose_name_plural': 'Timely Submission of Quarterly Report (TSQR) Calculations',
            },
        ),
    ]
