# Generated by Django 5.2.1 on 2025-07-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAWEC_KPI', '0004_calculatetsqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculateatc',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculateatc',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculatedscr',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculatedscr',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculategaf',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculategaf',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculatemwh',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculatemwh',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculatenecd',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculatenecd',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculatenpm',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculatenpm',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculateroa',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculateroa',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculatetde',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculatetde',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
    ]
