# Generated by Django 5.2.1 on 2025-07-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAWEC_KPI', '0005_calculateatc_progress_from_baseline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculateao',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculateao',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculatecr',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculatecr',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculatedd',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculatedd',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculateder',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculateder',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculatenrw',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculatenrw',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculatenwcd',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculatenwcd',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculatepari',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculatepari',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculatetps',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculatetps',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculatetsqr',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculatetsqr',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculatettp',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculatettp',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculatewqcb',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculatewqcb',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
        migrations.AddField(
            model_name='calculatewqcc',
            name='progress_from_baseline',
            field=models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True),
        ),
        migrations.AddField(
            model_name='calculatewqcc',
            name='progress_towards_end_target',
            field=models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True),
        ),
    ]
