# Generated by Django 5.2.1 on 2025-07-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAWEC_KPI', '0006_calculateao_progress_from_baseline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedscr',
            name='compensation_amount',
            field=models.FloatField(blank=True, help_text='Compensation amount', null=True),
        ),
        migrations.AddField(
            model_name='calculatenpm',
            name='compensation_amount',
            field=models.FloatField(blank=True, help_text='Compensation amount', null=True),
        ),
        migrations.AddField(
            model_name='calculateroa',
            name='compensation_amount',
            field=models.FloatField(blank=True, help_text='Compensation amount', null=True),
        ),
    ]
