# Generated by Django 5.2.1 on 2025-07-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAWEC_KPI', '0007_calculatedscr_compensation_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedscr',
            name='compensation_end_target',
            field=models.FloatField(blank=True, help_text='End target value based on compensation amount', null=True),
        ),
        migrations.AddField(
            model_name='calculatenpm',
            name='compensation_end_target',
            field=models.FloatField(blank=True, help_text='End target value based on compensation amount', null=True),
        ),
        migrations.AddField(
            model_name='calculateroa',
            name='compensation_end_target',
            field=models.FloatField(blank=True, help_text='End target value based on compensation amount', null=True),
        ),
    ]
