# Generated by Django 5.2.1 on 2025-07-29 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAWEC_KPI', '0008_calculatedscr_compensation_end_target_and_more'),
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], unique=True)),
                ('month_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Month',
                'verbose_name_plural': 'Months',
                'ordering': ['month_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='calculatemwh',
            options={'verbose_name': 'Local Production (Total electricity generated) (MWh) Calculation', 'verbose_name_plural': 'Local Production (Total electricity generated) (MWh) Calculations'},
        ),
        migrations.AlterField(
            model_name='calculateatc',
            name='billing_efficiency',
            field=models.FloatField(blank=True, help_text='Billing efficiency as percentage (≥0)', null=True),
        ),
        migrations.AlterField(
            model_name='calculateatc',
            name='collection_efficiency',
            field=models.FloatField(blank=True, help_text='Collection efficiency as percentage (≥0)', null=True),
        ),
        migrations.AlterField(
            model_name='calculatedd',
            name='total_credit_sales',
            field=models.FloatField(blank=True, help_text='Total Credit Sales amount', null=True),
        ),
        migrations.AlterField(
            model_name='calculatedd',
            name='trade_receivables',
            field=models.FloatField(blank=True, help_text='Trade Receivables amount', null=True),
        ),
        migrations.CreateModel(
            name='CalculateTMH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_value', models.FloatField(blank=True, help_text='Baseline value for comparison', null=True)),
                ('End_Target_Value', models.FloatField(blank=True, help_text='End target value to achieve', null=True)),
                ('achieved_value', models.FloatField(blank=True, help_text='Calculated training man hours result', null=True)),
                ('progress_from_baseline', models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True)),
                ('progress_towards_end_target', models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True)),
                ('training_sessions', models.FloatField(blank=True, help_text='Total training sessions conducted', null=True)),
                ('total_number_of_employees', models.FloatField(blank=True, help_text='Total number of employees', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.quarter')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.year')),
                ('month', models.ForeignKey(blank=True, help_text='Month for training data', null=True, on_delete=django.db.models.deletion.CASCADE, to='NAWEC_KPI.month')),
            ],
            options={
                'verbose_name': 'Training Man Hours (TMH) Calculation',
                'verbose_name_plural': 'Training Man Hours (TMH) Calculations',
            },
        ),
        migrations.DeleteModel(
            name='CalculateTDE',
        ),
    ]
