# Generated by Django 5.2.1 on 2025-07-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAWEC_KPI', '0009_month_alter_calculatemwh_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatetmh',
            name='training_sessions',
        ),
        migrations.AddField(
            model_name='calculatetmh',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duration of training sessions in hours', null=True),
        ),
        migrations.AddField(
            model_name='calculatetmh',
            name='participants',
            field=models.FloatField(blank=True, help_text='Number of participants', null=True),
        ),
        migrations.AddField(
            model_name='calculatetmh',
            name='total_training_days_conducted',
            field=models.FloatField(blank=True, help_text='Total training days conducted', null=True),
        ),
    ]
