# Generated by Django 5.2.1 on 2025-07-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAWEC_KPI', '0010_remove_calculatetmh_training_sessions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatetmh',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='calculatetmh',
            name='month',
        ),
        migrations.RemoveField(
            model_name='calculatetmh',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='calculatetmh',
            name='total_number_of_employees',
        ),
        migrations.RemoveField(
            model_name='calculatetmh',
            name='total_training_days_conducted',
        ),
        migrations.AddField(
            model_name='calculatetmh',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculatetmh',
            name='hours_per_day',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='calculatetmh',
            name='number_of_participants',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='calculatetmh',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculatetmh',
            name='title',
            field=models.CharField(default='Training Session', max_length=200),
        ),
    ]
