# Generated by Django 5.2.1 on 2025-07-30 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NAWEC_KPI', '0011_remove_calculatetmh_duration_and_more'),
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateIMPORTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_value', models.FloatField(blank=True, help_text='Baseline value for comparison', null=True)),
                ('End_Target_Value', models.FloatField(blank=True, help_text='End target value from database', null=True)),
                ('achieved_value', models.FloatField(blank=True, help_text='Calculated imports value in MW', null=True)),
                ('progress_from_baseline', models.FloatField(blank=True, help_text='Percentage progress from baseline', null=True)),
                ('progress_towards_end_target', models.FloatField(blank=True, help_text='Percentage progress towards end target', null=True)),
                ('add_value', models.FloatField(blank=True, help_text='Multiplier value for imports calculation', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('loginUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.quarter')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.year')),
            ],
            options={
                'verbose_name': 'Imports (MW) Calculation',
                'verbose_name_plural': 'Imports (MW) Calculations',
            },
        ),
    ]
