# Generated by Django 5.2.1 on 2025-07-07 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PIU_Financial_mgt', '0001_initial'),
        ('setup', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_description', models.CharField(max_length=500)),
                ('indicator_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.indicator_type')),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_descriptions', to=settings.AUTH_USER_MODEL)),
                ('pdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.pdo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project')),
                ('project_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.projectoutcome')),
                ('project_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.projectresult')),
            ],
            options={
                'verbose_name': 'Indicator Description',
                'verbose_name_plural': 'Indicator Descriptions',
            },
        ),
        migrations.CreateModel(
            name='Results_Oriented_Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_description', models.TextField(max_length=500)),
                ('baseline_value', models.FloatField(blank=True, null=True)),
                ('achieved_value', models.FloatField(blank=True, null=True)),
                ('End_Target_Value', models.FloatField(blank=True, null=True)),
                ('percentage_achieved_vs_baseline', models.FloatField(blank=True, null=True)),
                ('percentage_achieved_vs_end_target', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('collection_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.data_collection_frequency')),
                ('indicator_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.indicator_type')),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('measurement_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.measurement_unit')),
                ('pdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.pdo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project')),
                ('project_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.projectoutcome')),
                ('project_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.projectresult')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.quarter', verbose_name='Report Frequency')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.year')),
            ],
            options={
                'verbose_name': 'Results Oriented Monitoring',
                'verbose_name_plural': 'Results Oriented Monitoring',
            },
        ),
    ]
