# Generated by Django 5.2.1 on 2025-07-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PIU_Financial_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kpi_for_contract',
            table='PIU_Financial_mgt_kpi_for_contract',
        ),
    ]
