# Generated by Django 5.2.1 on 2025-07-07 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PIU_Financial_mgt', '0001_initial'),
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='issue_action_source',
            fields=[
                ('sourceID', models.AutoField(primary_key=True, serialize=False)),
                ('issue_action_source', models.CharField(max_length=100, verbose_name='Issue/Action Source')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('loginuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Issue/Action Source',
                'verbose_name_plural': 'Issue/Action Sources',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='IssueActions',
            fields=[
                ('issueID', models.AutoField(primary_key=True, serialize=False)),
                ('issue_code', models.CharField(max_length=100, verbose_name='Issue Code')),
                ('description_of_issue_or_action', models.TextField(verbose_name='Description of Issue/Action')),
                ('status', models.CharField(choices=[('complete', 'complete'), ('incomplete', 'incomplete'), ('Cancel', 'cancel')], default='incomplete', max_length=50, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Priority')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('issue_action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.kpi_for_contract', verbose_name='Issue/Action Type')),
                ('loginUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_issues', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIU_Financial_mgt.project')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.quarter')),
                ('source_of_issue_or_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Issues_Actions_monitoring.issue_action_source', verbose_name='Source of Issue/Action')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.year')),
            ],
            options={
                'verbose_name': 'Issue/Action',
                'verbose_name_plural': 'Issues/Actions',
                'ordering': ['-date_created'],
            },
        ),
    ]
