# Generated by Django 5.2.1 on 2025-07-08 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues_Actions_monitoring', '0001_initial'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueactions',
            name='assigned_to',
            field=models.CharField(default=1, max_length=100, verbose_name='Assigned To'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issueactions',
            name='issue_action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.type_of_monitoring', verbose_name='Issue/Action Type'),
        ),
    ]
