# Generated by Django 5.2.1 on 2025-07-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues_Actions_monitoring', '0002_alter_issueactions_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueactions',
            name='assign_date',
            field=models.DateField(blank=True, null=True, verbose_name='Assign Date'),
        ),
    ]
