# Generated by Django 5.2.1 on 2025-07-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues_Actions_monitoring', '0003_issueactions_assign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueactions',
            name='remarks',
            field=models.TextField(verbose_name='Remarks'),
        ),
    ]
